#---------------
#
# Test Configuration for BossRemoteFiles
#
#---------------
groupFileLink: "https://raw.githubusercontent.com/lrmtheboss/BossFiles/main/Testing/groupfile.yml"
#---------------
serverName: "TestServer"
#---------------
checkInterval: 120
#---------------